apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: 'quay.io/open-cluster-management/registration:latest'
  workImagePullSpec: 'quay.io/open-cluster-management/work:latest'